import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { runGenerate } from './generate.mjs';

// ── a workspace with an approved plan on disk ────────────────────────────────

function planFixture(runId = 'r1') {
  return {
    runId, createdAt: '2026-07-20T00:00:00Z', source: 'llm',
    features: [
      { featureId: 'feat:checkout', name: 'Checkout', source: 'llm', scenarios: [
        { scenarioId: 'sc-0001', title: 'cart loads', kind: 'api', intent: 'GET the cart', mutation: false, targets: { endpoints: ['GET /api/v2/cart'] }, priority: 0.9, gapRefs: [] },
        { scenarioId: 'sc-0002', title: 'place order', kind: 'api', intent: 'POST an order', mutation: true, targets: { endpoints: ['POST /api/v2/orders'] }, priority: 0.5, gapRefs: [] },
      ] },
      { featureId: 'feat:ops', name: 'Ops', source: 'llm', scenarios: [
        { scenarioId: 'sc-0003', title: 'health', kind: 'api', intent: 'GET health', mutation: false, targets: { endpoints: ['GET /api/v2/health'] }, priority: 0, gapRefs: [] },
      ] },
    ],
    estimates: { scenarios: 3, llmRequests: 8 },
  };
}

function makeWorkspace(t, plan = planFixture()) {
  const ws = fs.mkdtempSync(path.join(os.tmpdir(), 'c6-gen-'));
  t.after(() => fs.rmSync(ws, { recursive: true, force: true }));
  fs.mkdirSync(path.join(ws, 'plan'), { recursive: true });
  fs.writeFileSync(path.join(ws, 'plan', 'test-plan.json'), JSON.stringify(plan));
  return ws;
}

function readManifest(ws) {
  return JSON.parse(fs.readFileSync(path.join(ws, 'tests', 'manifest.json'), 'utf8'));
}

// A stand-in for runSession: writes files into tests/<featureId>/ exactly where
// the real session provider would, and returns filesWritten — so the honesty
// diff, parse gate, and manifest derivation behave identically to production.
function sessionWriting({ failFeatures = new Set(), fileKind = () => 'valid' } = {}) {
  return ({ workspace, slice }) => {
    if (failFeatures.has(slice.featureId)) {
      return { ok: false, error: 'engine-unavailable', detail: 'no session fixture' };
    }
    const filesWritten = [];
    for (const sc of slice.scenarios) {
      const kind = fileKind(sc.scenarioId);
      if (kind === 'missing') continue;
      const rel = path.join('tests', slice.featureId, `${sc.scenarioId}.spec.mjs`);
      const abs = path.join(workspace, rel);
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, kind === 'broken'
        ? 'export const x = ;;; this will not parse ('
        : `// agent\nexport const scenario = { id: '${sc.scenarioId}' };\nexport async function run() { return { ok: true }; }\n`);
      filesWritten.push(rel);
    }
    return { ok: true, filesWritten };
  };
}

const allScenarioIds = (plan) => plan.features.flatMap((f) => f.scenarios.map((s) => s.scenarioId));

// Every scenario in the plan must have EXACTLY one manifest entry (§1 honesty).
function assertComplete(manifest, plan) {
  const ids = manifest.entries.map((e) => e.scenarioId).sort();
  assert.deepEqual(ids, allScenarioIds(plan).sort());
  assert.equal(new Set(ids).size, ids.length, 'no duplicate manifest entries');
}

// ── happy path — every scenario generated by the agent ───────────────────────

test('all-agent: complete manifest, files on disk, no degradation', async (t) => {
  const ws = makeWorkspace(t);
  const res = await runGenerate({ workspace: ws, runId: 'r1', sessionFn: sessionWriting(), engine: {} });
  assert.equal(res.ok, true);
  assert.equal(res.degraded.length, 0);

  const m = readManifest(ws);
  assertComplete(m, planFixture());
  assert.ok(m.entries.every((e) => e.generator === 'agent' && e.status === 'generated'));
  // the files the manifest names really exist, under the raw (colon) featureId.
  for (const e of m.entries) assert.ok(fs.existsSync(path.join(ws, e.file)), `${e.file} exists`);
  // mcp-config + slice files were written.
  assert.ok(fs.existsSync(path.join(ws, 'mcp-config.json')));
  assert.ok(fs.existsSync(path.join(ws, 'plan', 'slices', 'feat-checkout.json')));
  assert.equal(res.stats.generated, 3);
});

// ── acceptance 1 — a failed slice falls back to templates, stage still ok ─────

test('failed slice → template fallback, complete manifest, degradation recorded', async (t) => {
  const ws = makeWorkspace(t);
  const res = await runGenerate({
    workspace: ws, runId: 'r1', engine: {},
    sessionFn: sessionWriting({ failFeatures: new Set(['feat:ops']) }),
  });
  assert.equal(res.ok, true);
  assertComplete(readManifest(ws), planFixture());

  const m = readManifest(ws);
  const ops = m.entries.filter((e) => e.featureId === 'feat:ops');
  assert.ok(ops.every((e) => e.generator === 'template' && e.status === 'generated'));
  // the checkout slice still came from the agent.
  assert.ok(m.entries.filter((e) => e.featureId === 'feat:checkout').every((e) => e.generator === 'agent'));

  assert.equal(res.degraded.length, 1);
  assert.equal(res.degraded[0].useCase, 'A1');
  assert.equal(res.degraded[0].stage, 'generate');
  // the templated file exists and parse-checks (it was written + gated).
  assert.ok(fs.existsSync(path.join(ws, ops[0].file)));
});

// ── partial: session ok but skips one scenario's file → that one templates ────

test('session leaves one scenario ungenerated → template just that scenario', async (t) => {
  const ws = makeWorkspace(t);
  const res = await runGenerate({
    workspace: ws, runId: 'r1', engine: {},
    sessionFn: sessionWriting({ fileKind: (id) => (id === 'sc-0002' ? 'missing' : 'valid') }),
  });
  assert.equal(res.ok, true);
  const m = readManifest(ws);
  assertComplete(m, planFixture());
  assert.equal(entryFor(m, 'sc-0001').generator, 'agent');
  assert.equal(entryFor(m, 'sc-0002').generator, 'template');   // the skipped one
  assert.equal(entryFor(m, 'sc-0003').generator, 'agent');
  assert.equal(res.degraded.length, 1);                          // one partial slice
});

// ── §4 validation: an unparseable agent file is rejected, then templated ──────

test('unparseable agent file → moved to _rejected, scenario templated', async (t) => {
  const ws = makeWorkspace(t);
  const res = await runGenerate({
    workspace: ws, runId: 'r1', engine: {},
    sessionFn: sessionWriting({ fileKind: (id) => (id === 'sc-0001' ? 'broken' : 'valid') }),
  });
  assert.equal(res.ok, true);
  const m = readManifest(ws);
  assertComplete(m, planFixture());

  const sc1 = entryFor(m, 'sc-0001');
  assert.equal(sc1.generator, 'template');                       // fell back
  assert.equal(sc1.status, 'generated');
  // the broken original was moved out of the executor's path.
  assert.ok(fs.existsSync(path.join(ws, 'tests', '_rejected', 'feat:checkout', 'sc-0001.spec.mjs')));
  assert.ok(res.degraded.length >= 1);
});

// ── acceptance 3 — resume regenerates only incomplete slices ──────────────────

test('resume: complete slices are skipped, incomplete ones regenerated', async (t) => {
  const ws = makeWorkspace(t);

  // First pass: everything generated.
  await runGenerate({ workspace: ws, runId: 'r1', sessionFn: sessionWriting(), engine: {} });

  // Simulate a kill BEFORE feat:ops finished: drop its manifest entries + file.
  const m1 = readManifest(ws);
  const trimmed = { ...m1, entries: m1.entries.filter((e) => e.featureId !== 'feat:ops') };
  fs.writeFileSync(path.join(ws, 'tests', 'manifest.json'), JSON.stringify(trimmed));
  fs.rmSync(path.join(ws, 'tests', 'feat:ops'), { recursive: true, force: true });

  // Second pass: checkout is unchanged (resumed); ops is regenerated. Spy on
  // which slices actually hit the session.
  const touched = [];
  const spy = (args) => { touched.push(args.slice.featureId); return sessionWriting()(args); };
  const res = await runGenerate({ workspace: ws, runId: 'r1', sessionFn: spy, engine: {} });

  assert.equal(res.stats.slicesResumed, 1);
  assert.deepEqual(touched, ['feat:ops']);          // only the incomplete slice ran
  assertComplete(readManifest(ws), planFixture());
});

// ── no plan ───────────────────────────────────────────────────────────────────

test('runGenerate fails cleanly when there is no approved plan', async (t) => {
  const ws = fs.mkdtempSync(path.join(os.tmpdir(), 'c6-noplan-'));
  t.after(() => fs.rmSync(ws, { recursive: true, force: true }));
  const res = await runGenerate({ workspace: ws, runId: 'r1', sessionFn: sessionWriting() });
  assert.equal(res.ok, false);
  assert.match(res.reason, /no approved plan/);
});

function entryFor(manifest, scenarioId) {
  return manifest.entries.find((e) => e.scenarioId === scenarioId);
}
